# Generated by Django 4.2.3 on 2023-08-14 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('image', models.ImageField(upload_to='subscriber_images')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('salary', models.FloatField()),
                ('subscription_date', models.DateField()),
                ('how_many_month', models.IntegerField()),
                ('expired_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expired',
            fields=[
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gym.subscriber')),
                ('expired_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Expired',
            },
        ),
    ]
