# Generated by Django 4.2.3 on 2023-08-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_customadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expired',
        ),
    ]
