# Generated by Django 4.2.3 on 2023-08-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_customadmin_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('image', models.ImageField(upload_to='admin_images')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomAdmin',
        ),
    ]
